### ISSUE TITLE
Screen Reports Incorrect Resolution

### ISSUE THREAD

**Issue by h4rryb** [pimoroni/presto#25]
According to the item description, it has a 480x480 display - however, when I run print(display.get_bounds()) (using jpegdec), it comes back as a 240x240 resolution - is there any way to configure this to be correct?

**Comment by MichaelBell** [comment]
By default Presto is in pixel double mode. Use `full_res=True` to put it in full resolution mode. See the vector clock full example: https://github.com/pimoroni/presto/blob/b4a41019de3b96eb6b987c0266195fb426b82548/examples/vector_clock_full.py#L9

**Comment by h4rryb** [comment]
> By default Presto is in pixel double mode. Use `full_res=True` to put it in full resolution mode. See the vector clock full example:
> 
> https://github.com/pimoroni/presto/blob/b4a41019de3b96eb6b987c0266195fb426b82548/examples/vector_clock_full.py#L9

I just found that on the Pimoroni forum and came back here to add it as a solution! Thanks for the speedy reply - the display looks super now!
